# Generated by Django 4.2.7 on 2023-11-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('slotrow', models.CharField()),
                ('slotcolumn', models.CharField()),
                ('parking_id', models.IntegerField()),
            ],
        ),
    ]
